In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer

In [2]:
class MyMinMaxScaler():
    def __init__(self, min = 0, max = 1):
        self.min = min
        self.max = max
        
    def fit(self, X):
        X_std = (X - X.min(axis = 0)) / (X.max(axis = 0) - X.min(axis = 0))
        X_ans = X_std * (self.max - self.min) + self.min
        return X_ans

class MyNormalizer():
    def __init__(self, type = 'l2'):
        self.type = type
    def fit(self, X):
        norms = None
        if(self.type == 'l2'):
            norms = np.sqrt(np.sum(np.square(X), axis = 1))
        elif(self.type == 'l1'):
            norms = np.sum(np.abs(X), axis=1)
        elif(self.type == 'max'):
            norms = np.max(X, axis = 1)
        else:
            return X
        norms[norms == 0.0] = 1.0
        X_ans = X / norms[:, np.newaxis]
        return X_ans

In [3]:
X = np.array([[ 1., -1.,  1.],
              [ 2.,  0.,  2.],
              [ 3.,  1., -1.]])

In [4]:
officialMinMaxScaler = MinMaxScaler(feature_range=(0, 1))
offcialNormalizerL2 = Normalizer(norm='l2')

myMinMaxScaler = MyMinMaxScaler(min = 0, max = 1)
myNormalizerL2 = MyNormalizer('l2')

In [5]:
print('officialMinMaxScaler Result: ')
print(officialMinMaxScaler.fit_transform(X))
print('-' * 50)
print('MyMinMaxScaler Result: ')
print(myMinMaxScaler.fit(X))

officialMinMaxScaler Result: 
[[0.         0.         0.66666667]
 [0.5        0.5        1.        ]
 [1.         1.         0.        ]]
--------------------------------------------------
MyMinMaxScaler Result: 
[[0.         0.         0.66666667]
 [0.5        0.5        1.        ]
 [1.         1.         0.        ]]


In [6]:
print('offcialNormalizerL2 Result: ')
print(offcialNormalizerL2.fit_transform(X))
print('-' * 50)
print('myNormalizerL2 Result: ')
print(myNormalizerL2.fit(X))

offcialNormalizerL2 Result: 
[[ 0.57735027 -0.57735027  0.57735027]
 [ 0.70710678  0.          0.70710678]
 [ 0.90453403  0.30151134 -0.30151134]]
--------------------------------------------------
myNormalizerL2 Result: 
[[ 0.57735027 -0.57735027  0.57735027]
 [ 0.70710678  0.          0.70710678]
 [ 0.90453403  0.30151134 -0.30151134]]
